package no.nordicsemi.nrf.matter.model

/*
 * Copyright (c) 2025, Nordic Semiconductor
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be
 * used to endorse or promote products derived from this software without specific prior
 * written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

data class ClusterType(
    val id: Long,
    val name: String,
) {
    companion object {
        fun parse(clusterId: Long): ClusterType =
            ClusterType(clusterId, StandardClusterNames.name(clusterId) ?: "Unknown Cluster")
    }
}

// https://project-chip.github.io/connectedhomeip-doc/ids_and_codes/spec_clusters.html for ver. 1.5
object StandardClusterNames {
    private val names: Map<Long, String> = mapOf(
        0x0003L to "Identify",
        0x0004L to "Groups",
        0x0006L to "On/Off",
        0x0008L to "Level Control",
        0x001DL to "Descriptor",
        0x001EL to "Binding",
        0x001FL to "Access Control",
        0x0025L to "Actions",
        0x0028L to "Basic Information",
        0x0029L to "OTA Software Update Provider",
        0x002AL to "OTA Software Update Requestor",
        0x002BL to "Localization Configuration",
        0x002CL to "Time Format Localization",
        0x002DL to "Unit Localization",
        0x002EL to "Power Source Configuration",
        0x002FL to "Power Source",
        0x0030L to "General Commissioning",
        0x0031L to "Network Commissioning",
        0x0032L to "Diagnostic Logs",
        0x0033L to "General Diagnostics",
        0x0034L to "Software Diagnostics",
        0x0035L to "Thread Network Diagnostics",
        0x0036L to "Wi-Fi Network Diagnostics",
        0x0037L to "Ethernet Network Diagnostics",
        0x0038L to "Time Synchronization",
        0x0039L to "Bridged Device Basic Information",
        0x003BL to "Switch",
        0x003CL to "Administrator Commissioning",
        0x003EL to "Operational Credentials",
        0x003FL to "Group Key Management",
        0x0040L to "Fixed Label",
        0x0041L to "User Label",
        0x0045L to "Boolean State",
        0x0046L to "ICD Management",
        0x0048L to "Oven Cavity Operational State",
        0x0049L to "Oven Mode",
        0x004AL to "Laundry Dryer Controls",
        0x0050L to "Mode Select",
        0x0051L to "Laundry Washer Mode",
        0x0052L to "Refrigerator And Temperature Controlled Cabinet Mode",
        0x0053L to "Laundry Washer Controls",
        0x0054L to "RVC Run Mode",
        0x0055L to "RVC Clean Mode",
        0x0056L to "Temperature Control",
        0x0057L to "Refrigerator Alarm",
        0x0059L to "Dishwasher Mode",
        0x005BL to "Air Quality",
        0x005CL to "Smoke CO Alarm",
        0x005DL to "Dishwasher Alarm",
        0x005EL to "Microwave Oven Mode",
        0x005FL to "Microwave Oven Control",
        0x0060L to "Operational State",
        0x0061L to "RVC Operational State",
        0x0062L to "Scenes Management",
        0x0071L to "HEPA Filter Monitoring",
        0x0072L to "Activated Carbon Filter Monitoring",
        0x0079L to "Water Tank Level Monitoring",
        0x0080L to "Boolean State Configuration",
        0x0081L to "Valve Configuration and Control",
        0x0090L to "Electrical Power Measurement",
        0x0091L to "Electrical Energy Measurement",
        0x0094L to "Water Heater Management",
        0x0095L to "Commodity Price",
        0x0097L to "Messages",
        0x0098L to "Device Energy Management",
        0x0099L to "Energy EVSE",
        0x009BL to "Energy Preference",
        0x009CL to "Power Topology",
        0x009DL to "Energy EVSE Mode",
        0x009EL to "Water Heater Mode",
        0x009FL to "Device Energy Management Mode",
        0x00A0L to "Electrical Grid Conditions",
        0x0101L to "Door Lock",
        0x0102L to "Window Covering",
        0x0104L to "Closure Control",
        0x0105L to "Closure Dimension",
        0x0150L to "Service Area",
        0x0200L to "Pump Configuration and Control",
        0x0201L to "Thermostat",
        0x0202L to "Fan Control",
        0x0204L to "Thermostat User Interface Configuration",
        0x0300L to "Color Control",
        0x0400L to "Illuminance Measurement",
        0x0402L to "Temperature Measurement",
        0x0403L to "Pressure Measurement",
        0x0404L to "Flow Measurement",
        0x0405L to "Relative Humidity Measurement",
        0x0406L to "Occupancy Sensing",
        0x040CL to "Carbon Monoxide Concentration Measurement",
        0x040DL to "Carbon Dioxide Concentration Measurement",
        0x0413L to "Nitrogen Dioxide Concentration Measurement",
        0x0415L to "Ozone Concentration Measurement",
        0x042AL to "PM2.5 Concentration Measurement",
        0x042BL to "Formaldehyde Concentration Measurement",
        0x042CL to "PM1 Concentration Measurement",
        0x042DL to "PM10 Concentration Measurement",
        0x042EL to "Total Volatile Organic Compounds Concentration Measurement",
        0x042FL to "Radon Concentration Measurement",
        0x0430L to "Soil Measurement",
        0x0451L to "Wi-Fi Network Management",
        0x0452L to "Thread Border Router Management",
        0x0453L to "Thread Network Directory",
        0x0503L to "Wake On LAN",
        0x0504L to "Channel",
        0x0505L to "Target Navigator",
        0x0506L to "Media Playback",
        0x0507L to "Media Input",
        0x0508L to "Low Power",
        0x0509L to "Keypad Input",
        0x050AL to "Content Launcher",
        0x050BL to "Audio Output",
        0x050CL to "Application Launcher",
        0x050DL to "Application Basic",
        0x050EL to "Account Login",
        0x050FL to "Content Control",
        0x0510L to "Content App Observer",
        0x0550L to "Zone Management",
        0x0551L to "Camera AV Stream Management",
        0x0552L to "Camera AV Settings User Level Management",
        0x0553L to "WebRTC Transport Provider",
        0x0554L to "WebRTC Transport Requestor",
        0x0555L to "Push AV Stream Transport",
        0x0556L to "Chime",
        0x0700L to "Commodity Tariff",
        0x0750L to "Ecosystem Information",
        0x0751L to "Commissioner Control",
        0x0752L to "Joint Fabric Datastore",
        0x0753L to "Joint Fabric Administrator",
        0x0801L to "TLS Certificate Management",
        0x0802L to "TLS Client Management",
        0x0B06L to "Meter Identification",
        0x0B07L to "Commodity Metering",
    )

    fun name(clusterId: Long): String? = names[clusterId]
}

// https://project-chip.github.io/connectedhomeip-doc/ids_and_codes/spec_device_types.html for ver. 1.5
object StandardDeviceTypeNames {
    private val names: Map<Long, String> = mapOf(
        0x000AL to "Door Lock",
        0x000BL to "Door Lock Controller",
        0x000EL to "Aggregator",
        0x000FL to "Generic Switch",
        0x0011L to "Power Source",
        0x0012L to "OTA Requestor",
        0x0013L to "Bridged Node",
        0x0014L to "OTA Provider",
        0x0015L to "Contact Sensor",
        0x0016L to "Root Node",
        0x0017L to "Solar Power",
        0x0018L to "Battery Storage",
        0x0019L to "Secondary Network Interface",
        0x0022L to "Speaker",
        0x0023L to "Casting Video Player",
        0x0024L to "Content App",
        0x0027L to "Mode Select",
        0x0028L to "Basic Video Player",
        0x0029L to "Casting Video Client",
        0x002AL to "Video Remote Control",
        0x002BL to "Fan",
        0x002CL to "Air Quality Sensor",
        0x002DL to "Air Purifier",
        0x0040L to "Irrigation System",
        0x0041L to "Water Freeze Detector",
        0x0042L to "Water Valve",
        0x0043L to "Water Leak Detector",
        0x0044L to "Rain Sensor",
        0x0045L to "Soil Sensor",
        0x0070L to "Refrigerator",
        0x0071L to "Temperature Controlled Cabinet",
        0x0072L to "Room Air Conditioner",
        0x0073L to "Laundry Washer",
        0x0074L to "Robotic Vacuum Cleaner",
        0x0075L to "Dishwasher",
        0x0076L to "Smoke CO Alarm",
        0x0077L to "Cook Surface",
        0x0078L to "Cooktop",
        0x0079L to "Microwave Oven",
        0x007AL to "Extractor Hood",
        0x007BL to "Oven",
        0x007CL to "Laundry Dryer",
        0x0090L to "Network Infrastructure Manager",
        0x0091L to "Thread Border Router",
        0x0100L to "On/Off Light",
        0x0101L to "Dimmable Light",
        0x0103L to "On/Off Light Switch",
        0x0104L to "Dimmer Switch",
        0x0105L to "Color Dimmer Switch",
        0x0106L to "Light Sensor",
        0x0107L to "Occupancy Sensor",
        0x010AL to "On/Off Plug-in Unit",
        0x010BL to "Dimmable Plug-In Unit",
        0x010CL to "Color Temperature Light",
        0x010DL to "Extended Color Light",
        0x010FL to "Mounted On/Off Control",
        0x0110L to "Mounted Dimmable Load Control",
        0x0130L to "Joint Fabric Administrator",
        0x0140L to "Intercom",
        0x0141L to "Audio Doorbell",
        0x0142L to "Camera",
        0x0143L to "Video Doorbell",
        0x0144L to "Floodlight Camera",
        0x0145L to "Snapshot Camera",
        0x0146L to "Chime",
        0x0147L to "Camera Controller",
        0x0148L to "Doorbell",
        0x0202L to "Window Covering",
        0x0203L to "Window Covering Controller",
        0x0230L to "Closure",
        0x0231L to "Closure Panel",
        0x023EL to "Closure Controller",
        0x0301L to "Thermostat",
        0x0302L to "Temperature Sensor",
        0x0303L to "Pump",
        0x0304L to "Pump Controller",
        0x0305L to "Pressure Sensor",
        0x0306L to "Flow Sensor",
        0x0307L to "Humidity Sensor",
        0x0309L to "Heat Pump",
        0x030AL to "Thermostat Controller",
        0x050CL to "Energy EVSE",
        0x050DL to "Device Energy Management",
        0x050FL to "Water Heater",
        0x0510L to "Electrical Sensor",
        0x0511L to "Electrical Utility Meter",
        0x0512L to "Meter Reference Point",
        0x0513L to "Electrical Energy Tariff",
        0x0514L to "Electrical Meter",
        0x0840L to "Control Bridge",
        0x0850L to "On/Off Sensor"
    )

    fun name(deviceTypeId: Long): String? = names[deviceTypeId]
}
