package no.nordicsemi.nrf.matter.model

/*
 * Copyright (c) 2025, Nordic Semiconductor
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be
 * used to endorse or promote products derived from this software without specific prior
 * written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

data class ClusterType(
    val id: Long,
    val name: String,
) {
    companion object {
        fun parse(clusterId: Long): ClusterType =
            ClusterType(clusterId, StandardClusterNames.name(clusterId) ?: "Unknown Cluster")
    }
}

object StandardClusterNames {
    private val names: Map<Long, String> = mapOf(
        3L to "Identify",
        4L to "Groups",
        6L to "On/Off",
        8L to "Level Control",
        28L to "Pulse Width Modulation",
        29L to "Descriptor",
        30L to "Binding",
        31L to "Access Control",
        37L to "Actions",
        40L to "Basic Information",
        41L to "OTA Software Update Provider",
        42L to "OTA Software Update Requestor",
        43L to "Localization Configuration",
        44L to "Time Format Localization",
        45L to "Unit Localization",
        46L to "Power Source Configuration",
        47L to "Power Source",
        48L to "General Commissioning",
        49L to "Network Commissioning",
        50L to "Diagnostic Logs",
        51L to "General Diagnostics",
        52L to "Software Diagnostics",
        53L to "Thread Network Diagnostics",
        54L to "Wi-Fi Network Diagnostics",
        55L to "Ethernet Network Diagnostics",
        56L to "Time Synchronization",
        57L to "Bridged Device Basic Information",
        59L to "Switch",
        60L to "Administrator Commissioning",
        62L to "Operational Credentials",
        63L to "Group Key Management",
        64L to "Fixed Label",
        65L to "User Label",
        66L to "Proxy Configuration",
        67L to "Proxy Discovery",
        68L to "Proxy Valid",
        69L to "Boolean State",
        70L to "ICD Management",
        71L to "Timer",
        72L to "Oven Cavity Operational State",
        73L to "Oven Mode",
        74L to "Laundry Dryer Controls",
        80L to "Mode Select",
        81L to "Laundry Washer Mode",
        82L to "Refrigerator and Temperature Controlled Cabinet Mode",
        83L to "Laundry Washer Controls",
        84L to "RVC Run Mode",
        85L to "RVC Clean Mode",
        86L to "Temperature Control",
        87L to "Refrigerator Alarm",
        89L to "Dishwasher Mode",
        91L to "Air Quality",
        92L to "Smoke CO Alarm",
        93L to "Dishwasher Alarm",
        94L to "Microwave Oven Mode",
        95L to "Microwave Oven Control",
        96L to "Operational State",
        97L to "RVC Operational State",
        98L to "Scenes Management",
        101L to "Group Cast",
        113L to "HEPA Filter Monitoring",
        114L to "Activated Carbon Filter Monitoring",
        121L to "Water Tank Level Monitoring",
        128L to "Boolean State Configuration",
        129L to "Valve Configuration and Control",
        144L to "Electrical Power Measurement",
        145L to "Electrical Energy Measurement",
        148L to "Water Heater Management",
        149L to "Commodity Price",
        151L to "Messages",
        152L to "Device Energy Management",
        153L to "Energy EVSE",
        155L to "Energy Preference",
        156L to "Power Topology",
        157L to "Energy EVSE Mode",
        158L to "Water Heater Mode",
        159L to "Device Energy Management Mode",
        160L to "Electrical Grid Conditions",
        257L to "Door Lock",
        258L to "Window Covering",
        260L to "Closure Control",
        261L to "Closure Dimension",
        336L to "Service Area",
        512L to "Pump Configuration and Control",
        513L to "Thermostat",
        514L to "Fan Control",
        516L to "Thermostat User Interface Configuration",
        768L to "Color Control",
        769L to "Ballast Configuration",
        1024L to "Illuminance Measurement",
        1026L to "Temperature Measurement",
        1027L to "Pressure Measurement",
        1028L to "Flow Measurement",
        1029L to "Relative Humidity Measurement",
        1030L to "Occupancy Sensing",
        1036L to "Carbon Monoxide Concentration Measurement",
        1037L to "Carbon Dioxide Concentration Measurement",
        1043L to "Nitrogen Dioxide Concentration Measurement",
        1045L to "Ozone Concentration Measurement",
        1066L to "PM2.5 Concentration Measurement",
        1067L to "Formaldehyde Concentration Measurement",
        1068L to "PM1 Concentration Measurement",
        1069L to "PM10 Concentration Measurement",
        1070L to "Total Volatile Organic Compounds Concentration Measurement",
        1071L to "Radon Concentration Measurement",
        1072L to "Soil Measurement",
        1105L to "Wi-Fi Network Management",
        1106L to "Thread Border Router Management",
        1107L to "Thread Network Directory",
        1283L to "Wake on LAN",
        1284L to "Channel",
        1285L to "Target Navigator",
        1286L to "Media Playback",
        1287L to "Media Input",
        1288L to "Low Power",
        1289L to "Keypad Input",
        1290L to "Content Launcher",
        1291L to "Audio Output",
        1292L to "Application Launcher",
        1293L to "Application Basic",
        1294L to "Account Login",
        1295L to "Content Control",
        1296L to "Content App Observer",
        1360L to "Zone Management",
        1361L to "Camera AV Stream Management",
        1362L to "Camera AV Settings User Level Management",
        1363L to "WebRTC Transport Provider",
        1364L to "WebRTC Transport Requestor",
        1365L to "Push AV Stream Transport",
        1366L to "Chime",
        1792L to "Commodity Tariff",
        1872L to "Ecosystem Information",
        1873L to "Commissioner Control",
        1874L to "Joint Fabric Datastore",
        1875L to "Joint Fabric Administrator",
        2049L to "TLS Certificate Management",
        2050L to "TLS Client Management",
        2822L to "Meter Identification",
        2823L to "Commodity Metering",
    )

    fun name(clusterId: Long): String? = names[clusterId]
}

object StandardDeviceTypeNames {
    private val names: Map<Long, String> = mapOf(
        0x0016L to "Root Node",
        0x0011L to "Power Source",
        0x0510L to "Electrical Sensor",
        0x0012L to "OTA Requestor",
        0x0014L to "OTA Provider",
        0x000EL to "Aggregator",
        0x0013L to "Bridged Node",
        0x0020L to "Streaming Audio Player",
        0x0021L to "Casting Audio Player",
        0x0040L to "Irrigation System",
        0x007DL to "Humidity Conditioner",
        0x0092L to "Commissioning By Proxy",
        0x0100L to "On/Off Light",
        0x0101L to "Dimmable Light",
        0x010CL to "Color Temperature Light",
        0x010DL to "Extended Color Light",
        0x010AL to "On/Off Plug-in Unit",
        0x010BL to "Dimmable Plug-in Unit",
        0x010FL to "Mounted On/Off Control",
        0x0110L to "Mounted Dimmable Load Control",
        0x0140L to "Intercom",
        0x0141L to "Audio Doorbell",
        0x0142L to "Camera",
        0x0143L to "Video Doorbell",
        0x0144L to "Floodlight Camera",
        0x0145L to "Snapshot Camera",
        0x0146L to "Chime",
        0x0147L to "Camera Controller",
        0x0148L to "Doorbell",
        0x0149L to "AV Analysis Node",
        0x0150L to "Ambient Context Sensor",
        0x0152L to "Proximity Ranger",
        0x0230L to "Closure",
        0x0231L to "Closure Panel",
        0x023EL to "Closure Controller",
        0x0303L to "Pump",
        0x0103L to "On/Off Light Switch",
        0x0104L to "Dimmer Switch",
        0x0105L to "Color Dimmer Switch",
        0x0511L to "Electrical Utility Meter",
        0x0512L to "Meter Reference Point",
        0x0513L to "Electrical Energy Tariff",
        0x0514L to "Electrical Meter",
        0x0515L to "Arc Fault Circuit Interrupter",
        0x0516L to "Electrical Circuit Breaker",
        0x0517L to "Electrical Distribution Enclosure",
        0x0518L to "Electrical Surge Protector",
        0x0519L to "Residual Current Circuit Breaker",
        0x0520L to "Auxiliary Load Switch",
        0x0840L to "Control Bridge",
        0x0304L to "Pump Controller",
        0x000FL to "Generic Switch",
        0x0015L to "Contact Sensor",
        0x0106L to "Light Sensor",
        0x0107L to "Occupancy Sensor",
        0x0302L to "Temperature Sensor",
        0x0305L to "Pressure Sensor",
        0x0306L to "Flow Sensor",
        0x0307L to "Humidity Sensor",
        0x0850L to "On/Off Sensor",
        0x000AL to "Door Lock",
        0x000BL to "Door Lock Controller",
        0x0202L to "Window Covering",
        0x0203L to "Window Covering Controller",
        0x0301L to "Thermostat",
        0x002BL to "Fan",
        0x0023L to "Casting Video Player",
        0x0028L to "Basic Video Player",
        0x0029L to "Casting Video Client",
        0x002AL to "Video Remote Control",
        0x0022L to "Speaker",
        0x0024L to "Content App",
        0x0027L to "Mode Select",
        0x0072L to "Room Air Conditioner",
        0x0076L to "Smoke CO Alarm",
        0x002DL to "Air Purifier",
        0x002CL to "Air Quality Sensor",
        0x0075L to "Dishwasher",
        0x007BL to "Oven",
        0x0079L to "Microwave Oven",
        0x0070L to "Refrigerator",
        0x0073L to "Laundry Washer",
        0x007CL to "Laundry Dryer",
        0x007AL to "Extractor Hood",
        0x0074L to "Robotic Vacuum Cleaner",
        0x0071L to "Temperature Controlled Cabinet",
        0x0041L to "Water Freeze Detector",
        0x0042L to "Water Valve",
        0x0043L to "Water Leak Detector",
        0x0044L to "Rain Sensor",
        0x0090L to "Network Infrastructure Manager",
        0x0091L to "Thread Border Router",
        0x0019L to "Secondary Network Interface",
        0x0130L to "Joint Fabric Administrator",
        0x0078L to "Cooktop",
        0x0077L to "Cook Surface",
        0x050CL to "EVSE",
        0x050DL to "Device Energy Management",
        0x050FL to "Water Heater",
        0x0309L to "Heat Pump",
        0x0017L to "Solar Power",
        0x0018L to "Battery Storage",
        0x030AL to "Thermostat Controller",
        0x0045L to "Soil Sensor",
    )

    fun name(deviceTypeId: Long): String? = names[deviceTypeId]
}
