default_platform(:android)

platform :android do

  desc "Build release bundle"
  lane :buildRelease do
    gradle(
      task: "androidApp:bundle",
      build_type: "Release"
    )
  end

  desc "Deploy to Google Play Internal track"
  lane :deployInternal do

    gradle(
      task: "clean androidApp:bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",
      aab: "androidApp/build/outputs/bundle/release/androidApp-release.aab",
    )
  end

  desc "Deploy to production"
  lane :deploy do
    gradle(
      task: "clean androidApp:bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "production",
      aab: "androidApp/build/outputs/bundle/release/androidApp-release.aab",
    )
  end

  desc "Deploy libraries to Nexus."
  lane :deployNexus do
    gradle(task: "publish")
    gradle(task: "releaseStagingRepositories")
  end

  desc "Generate docs."
  lane :generateDocs do
    gradle(task: "dokkaHtmlMultiModule")
  end
end
